# 1. NumPy exercises

In [1]:
#import the Numpy package
import numpy as np

In [2]:
#Set the random seed
np.random.seed(859)

In [4]:
# 1. Create a random array (uniform distribution) of 100 values between 0 and 1
arr_1 = np.linspace(0,1,100)

#Display the resulting array
arr_1

array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
       0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
       0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
       0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
       0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
       0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
       0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
       0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
       0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
       0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
       0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
       0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
       0.70707071, 0.71717172, 0.72727273, 0.73737374, 0.74747

In [5]:
#2. Report the shape of the resulting array
arr_1.shape

(100,)

In [7]:
#3. Report the data type of the resulting array
arr_1.dtype

dtype('float64')

In [9]:
#4. Report the mean value of all values in your array
arr_1.mean()

0.5

In [10]:
#5. Multiply each value in your array by 10 so its values range from 0 and 10, saving the results as "arr_2"
arr_2 = arr_1 * 10
#Display the array
arr_2

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

In [11]:
#6. Reshape the "arr_2" array to be 25 rows and 4 columns, saving the result as "arr_3"
arr_3 = arr_2.reshape(25,4)

In [24]:
arr_3

array([[ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ],
       [ 0.4040404 ,  0.50505051,  0.60606061,  0.70707071],
       [ 0.80808081,  0.90909091,  1.01010101,  1.11111111],
       [ 1.21212121,  1.31313131,  1.41414141,  1.51515152],
       [ 1.61616162,  1.71717172,  1.81818182,  1.91919192],
       [ 2.02020202,  2.12121212,  2.22222222,  2.32323232],
       [ 2.42424242,  2.52525253,  2.62626263,  2.72727273],
       [ 2.82828283,  2.92929293,  3.03030303,  3.13131313],
       [ 3.23232323,  3.33333333,  3.43434343,  3.53535354],
       [ 3.63636364,  3.73737374,  3.83838384,  3.93939394],
       [ 4.04040404,  4.14141414,  4.24242424,  4.34343434],
       [ 4.44444444,  4.54545455,  4.64646465,  4.74747475],
       [ 4.84848485,  4.94949495,  5.05050505,  5.15151515],
       [ 5.25252525,  5.35353535,  5.45454545,  5.55555556],
       [ 5.65656566,  5.75757576,  5.85858586,  5.95959596],
       [ 6.06060606,  6.16161616,  6.26262626,  6.36363636],
       [ 6.46464646,  6.

In [25]:
#7. Show the 3rd row of this (arr_3) array
arr_3[2]

array([0.80808081, 0.90909091, 1.01010101, 1.11111111])

In [26]:
#8. Show the values in the 2nd column of this array
arr_3[:,1]

array([0.1010101 , 0.50505051, 0.90909091, 1.31313131, 1.71717172,
       2.12121212, 2.52525253, 2.92929293, 3.33333333, 3.73737374,
       4.14141414, 4.54545455, 4.94949495, 5.35353535, 5.75757576,
       6.16161616, 6.56565657, 6.96969697, 7.37373737, 7.77777778,
       8.18181818, 8.58585859, 8.98989899, 9.39393939, 9.7979798 ])

In [28]:
#9. Show the mean of the values in the 2nd column
arr_3[:,1].mean()

4.949494949494949